### PR TITLE
Feature/1.1/#27 add medium reason to cli interface

### LINKED ISSUE #27: Add "medium" and "reason" to the CLI interace
After #25, we'll add the new options to to the CLI interface so people can actually use them.

This will likely be as simple as adding the following two options:
* `--medium <medium-type>` -- defaults to `"podcast"`
* `--reason <reason-code>` -- defaults to `"update"`

We will validate the available slugs to avoid any errors.

### PR DESCRIPTION
**Pull request by agates**
Closes #27

### CODE REVIEW

**Comment by brianoflondon** [comment]
Added to the CLI help otherwise all looks good.

**Comment by brianoflondon** [comment]
I think I've reviewed everything now.

**Review by brianoflondon — APPROVED** [review]
I added the doc string and removed one unused import of base64

**Comment by brianoflondon** [comment]
I'm trying to figure out why tests are suddenly failing.

**Comment by agates** [comment]
Is it just a timeout thing? I'll look into it too

**Comment by brianoflondon** [comment]
It's not just timeout. Fix coming soon.

when trx_id return from the post to Hive was removed it still remained in 

```
    async def _iri_batch_handler_loop(self):
```

but within a `try:` block so that loop failed silently and never ran again.

**Comment by brianoflondon** [comment]
And by the way the only way I could debug and find this was by my old fashioned method of running the server in debug mode and having another hive-watcher running and sending URLs in via the ZMQ queue. I could see the batch handler run once then crap out.

**Pull request merged**
