### PR TITLE
This is my quick fix for infinite loop when internet goes down

### PR DESCRIPTION
**Pull request by brianoflondon**
I need to learn the best way to propose changes like these

### CODE REVIEW

**Comment by brianoflondon** [comment]
These changes have been running non stop for days and survived a number of internet outages (restarting the router) without needing the docker container to auto-restart.

```
podping-3spk         | 2021-09-29T04:41:29+0000 | INFO | Status - Uptime: 6 days, 21:50:50.723066 - IRIs Received: 362 - IRIs Deduped: 361 - IRIs Sent: 361 - https://api.openhive.network
podping-3spk         | 2021-09-29T04:43:40+0000 | INFO | Status - Uptime: 6 days, 21:53:01.740419 - IRIs Received: 362 - IRIs Deduped: 361 - IRIs Sent: 361 - https://api.hive.blog
```

I also prefer this diagnostic output:
```
podping-3spk         | 2021-09-29T04:40:33+0000 | INFO | Batch send time: 0.67 - trx_id: 574e8e918f52d316300236ca6b2991a505e94d49 - Failures: 0 - IRI batch_id 8cb5e0b0-17ad-4e07-b6cb-2e7baff09d54 - IRIs in batch: 2 - https://hive-api.arcange.eu
```

Because it tells me the API node AND the time it took to process a batch in one line.

**Comment by agates** [comment]
Fixes #22

**Comment by daveajones** [comment]
My my, you’re a busy boy on Christmas Eve.

**Comment by brianoflondon** [comment]
Lol first I knew was when the Hive account for podping.git which is used for CI tests suddenly screamed about resource credit depletion. 

>- Level 3  ***
********** Mana Bar for podping.gittest  |  78.8 % | -123.77281 %/hr  | in one hour: -45.0 % | HP:      30.0


Btw I monitor all the main Podping accounts. 

I gave it a bit more juice but it probably wasn't necessary as Alecks trends not to run crazy amounts of commit tests.

**Pull request merged**
